spring:
  application:
    name: service-mms
  profiles:
    active: dev
          
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: 
mybatis-plus:
  type-aliases-package: 
  mapper-locations: classpath:mapper/*.xml
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
  global-config:
    refresh-mapper: true
     #驼峰下划线转换
    column-underline: true
  configuration:
     map-underscore-to-camel-case: true
