server:
  port: 8762
spring:
  application:
    name: member
  redis:
    host: 192.168.25.128
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1